### ISSUE TITLE
Update releases with latest changes? 

### ISSUE THREAD

**Issue by BahrawiElimi** [K1DV5/extreme#1]
I want to ask why the svg view has been canceled It was preserving the layout

**Comment by K1DV5** [comment]
Hello, I assume you're talking about replacing images with placeholders which you could long press to show the image. It was cancelled because I noticed that it wasn't used that much (at least not for me) and if there is a need to show the image, you could turn images on, apply and reload, which works for the specific domain on the specific tab. I agree that it has the downside of downloading all the images on the page but considering the amount of code for the feature in question and how much it is used, I think it's a good compromise.

**Comment by BahrawiElimi** [comment]
Yeah, I meant it.
Anyway it works well and contributes to data saving greatly after Google stop googleweblight support

**Comment by K1DV5** [comment]
Thanks, it's what I'm using and I'm glad it's useful to you too.
Closing.
